Repository mokumoku-lovers/moku-moku-users, pull requests merged in 2021-08, with the labels that each got.

#25 Create user
  .gitignore
  datasources/postgresql/users_db/users_db.go
  datasources/postgresql/users_db/users_db.sql
  datasources/postresql/users_db/users_db.sql
  domain/users/user_dao.go
  domain/users/user_dto.go
  go.mod
  go.sum
  utils/date_utils/date_utils.go
  utils/errors/errors.go
  utils/pg_utils/pg_utils.go
Labels: DB, enhancement

#28 Delete User
  app/routing.go
  controllers/users/UserController.go
  domain/users/user_dao.go
  services/UserService.go
Labels: DB, enhancement

#29 Feature/update user sql/16
  app/routing.go
  controllers/users/UserController.go
  domain/users/user_dao.go
  services/UserService.go
Labels: DB, enhancement

#31 Feature/get user sql/17
  domain/users/user_dao.go
  go.mod
  go.sum
Labels: enhancement, Task

#32 feature/patch_user/6
  app/routing.go
  controllers/users/UserController.go
  domain/users/user_dao.go
  services/UserService.go
Labels: enhancement, Task

#35 Birthday field control in user creation endpoint
  domain/users/user_dao.go
Labels: enhancement, DB, fix

#36 Feature/update points/34
  app/routing.go
  controllers/users/UserController.go
Labels: enhancement, DB

#37 Feature/update password/33
  .gitignore
  app/routing.go
  controllers/users/UserController.go
  domain/users/user_dao.go
  domain/users/user_dto.go
  services/UserService.go
Labels: enhancement, Task, DB

#38 Feature/user marshaling/26
  controllers/users/UserController.go
  domain/users/user_marshaller.go
Labels: enhancement, Task

#39 return password change successful string
  controllers/users/UserController.go
Labels: fix

#40 Documentation/swagger api/27
  app/routing.go
  controllers/users/UserController.go
  domain/users/user_dto.go
  go.mod
  go.sum
  swagger.yml
Labels: documentation

#41 Moku Moku Users API v0.1.0
  .gitignore
  app/app.go
  app/routing.go
  controllers/users/UserController.go
  datasources/postgresql/users_db/users_db.go
  datasources/postgresql/users_db/users_db.sql
  domain/users/user_dao.go
  domain/users/user_dto.go
  domain/users/user_marshaller.go
  go.mod
  go.sum
  main.go
  services/UserService.go
  swagger.yml
  utils/date_utils/date_utils.go
  utils/errors/errors.go
  utils/pg_utils/pg_utils.go
Labels: Release
